version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - ./config/nginx:/etc/nginx/conf.d
  node:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/home/node/app
    command: "yarn start"
